server:
  port: 7777
  servlet:
    context-path: /scala-boot
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/boot-scala?useUnicode=true&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
